/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTable;

/**
 *
 * @author Sebastian Leal S
 */
public class tableConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form tableConsulta
     */
    public tableConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoVeh = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistro = new javax.swing.JTable();
        lblTipoVeh = new javax.swing.JLabel();
        rbtnCarro = new javax.swing.JRadioButton();
        rbtnMoto = new javax.swing.JRadioButton();
        btnFliltrar = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(631, 402));

        tablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Propietario", "Tipo Veh", "Placa", "Marca", "Modelo", "Cilindraje", "Valor", "Impuesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaRegistro);

        lblTipoVeh.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        lblTipoVeh.setText("Tipo Vehiculo");

        rbtnCarro.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        rbtnCarro.setText("Carro");
        rbtnCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCarroActionPerformed(evt);
            }
        });

        rbtnMoto.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        rbtnMoto.setText("Moto");

        btnFliltrar.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        btnFliltrar.setText("Fliltrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoVeh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnMoto)
                        .addGap(18, 18, 18)
                        .addComponent(btnFliltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVeh)
                    .addComponent(rbtnCarro)
                    .addComponent(rbtnMoto)
                    .addComponent(btnFliltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCarroActionPerformed

    public JButton getBtnFliltrar() {
        return btnFliltrar;
    }

    public void setBtnFliltrar(JButton btnFliltrar) {
        this.btnFliltrar = btnFliltrar;
    }

    public ButtonGroup getBtngTipoVeh() {
        return btngTipoVeh;
    }

    public void setBtngTipoVeh(ButtonGroup btngTipoVeh) {
        this.btngTipoVeh = btngTipoVeh;
    }

    public JRadioButton getRbtnCarro() {
        return rbtnCarro;
    }

    public void setRbtnCarro(JRadioButton rbtnCarro) {
        this.rbtnCarro = rbtnCarro;
    }

    public JRadioButton getRbtnMoto() {
        return rbtnMoto;
    }

    public void setRbtnMoto(JRadioButton rbtnMoto) {
        this.rbtnMoto = rbtnMoto;
    }

    public JTable getTablaRegistro() {
        return tablaRegistro;
    }

    public void setTablaRegistro(JTable tablaRegistro) {
        this.tablaRegistro = tablaRegistro;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFliltrar;
    private javax.swing.ButtonGroup btngTipoVeh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoVeh;
    private javax.swing.JRadioButton rbtnCarro;
    private javax.swing.JRadioButton rbtnMoto;
    private javax.swing.JTable tablaRegistro;
    // End of variables declaration//GEN-END:variables
}
